# version format
version: 1.0.{build}

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm install -g typescript
  - npm install -g gulp
  - npm install
  
# Post-install test scripts.
#test_script:
  # Output useful info for debugging.
#  - node --version
#  - npm --version
  # run tests
#  - npm test

# Don't actually build.
build_script:
  - node_modules\.bin\gulp build_release
  - node_modules\.bin\gulp restore_release

test_script:
  - node_modules\.bin\gulp test

after_test:  
  - ps: .\build\build.ps1
  - ps: nuget.exe pack funcgraph.compiled.nuspec

artifacts:
- path: .\*.nupkg
  name: NuGet
  type: NuGetPackage

deploy:
  release: funcgraph-v$(appveyor_build_version)
  description: 'Commit build'
  provider: GitHub
  auth_token: 
    secure: R1Od4gYaFkuhqpFUVBJpVZY4CRAeHuzgH4VQBMfWWXwEAEY4iVJo8sNBq4N+4enq # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only 